### ISSUE TITLE
Server compete lockup. landmaster.landcraft.item.ItemLandmastersWings.renderPlayerLasers()100.00%

### ISSUE THREAD

**Issue by ProsperCraft** [Landmaster/LandCraft#16] opened 2018-02-07 03:12 UTC
This is a warmroast run from the outside to profile the server while it was 100% locked hard.

https://i.gyazo.com/72d00c3be36db31fd2e0c1d6f990a317.png
![warmroast](https://user-images.githubusercontent.com/4427684/35896377-185920c8-0b79-11e8-9d9a-f030502092fa.png)

I left it locked up for a good 30 minutes it did not recover.

This is the console right before it locked -

https://gist.github.com/ProsperCraft/6ef8b61cc3ff91ea28eefa4700f2fed4

Find attached logs if you want them.
[2018-02-06-4.log.gz](https://github.com/Landmaster/LandCraft/files/1701580/2018-02-06-4.log.gz)

This is the pack we are using your mod with - 
https://minecraft.curseforge.com/projects/towncraft

**Comment by Landmaster** [comment] 2018-02-07 13:41
@ProsperCraft Try reproducing the deadlock with only LandCore and LandCraft.

**Comment by ProsperCraft** [comment] 2018-02-07 13:55
I don't know how this would be possible as we have hundreds of hours of playtime, and this has only happened once so far.

**Comment by Landmaster** [comment] 2018-02-07 14:41
@ProsperCraft For how long have you used the item Landmaster's Wings?

**Comment by ProsperCraft** [comment] 2018-02-07 16:10
When asked the players say they have not used them.

**Comment by Landmaster** [comment] 2018-02-07 21:16
@ProsperCraft Is there anything else below the current screenshot?

**Comment by ProsperCraft** [comment] 2018-02-07 23:08
No it hard locked, would not recover, had to kill -9 the pid.

**Comment by Landmaster** [comment] 2018-02-09 01:16
@ProsperCraft From the looks of the log, it seems to be a problem with Netty not directly related to LandCraft. What were the players doing right when the server locked up?

**Comment by ProsperCraft** [comment] 2018-02-09 03:22
I honestly don't know.  But nobody has made any landmasters wings.

**Comment by ProsperCraft** [comment] 2018-02-16 06:53
Here was a player getting kicked, and the stacktrace from that in console.
He does not have any landmasters wings, and no player on the server had.

https://gist.github.com/ProsperCraft/6104d0b2c4b3da909bdd4453ce5ea396

**Comment by Landmaster** [comment] 2019-03-23 12:27
Probably related to #18, closing until further notice.

**Closed by Landmaster** 2019-03-23 12:27 UTC
